services:
  node:
    build:
      context: ../..
      dockerfile: docker/dev/node/Dockerfile
    image: syniol_node:22
    container_name: nestjs_node
    tty: true
    environment:
      NODE_ENV: development
      PORT: 8080
    working_dir: /var/local/app
    ports:
      - 8080:8080
    volumes:
      - ../../app:/var/local/app
    networks:
      - default_nestjs_syniol_net

networks:
  default_nestjs_syniol_net:
    driver: bridge
